import localFont from "next/font/local";
import "./globals.css";
import MainHeader from "@/components/main-header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "03 - Routing Rendering",
  description: "Generated by create next app - Augusto Iseppe Balan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="page">
        <MainHeader /> {/* O MAIN-HEADER FICARÁ DISPONÍVEL PARA TODAS AS PAGINAS ATRAVES DESTE ARQUIVO layout.js */}
        {children}
        </div>
      </body>
    </html>
  );
}
